qemu-img: update to 2.7.0
Adds support for VHD images
Also, doing a conversion to using HOST_CONFIGURE_* make vars

The `--without-pixman` option requires 2 more options to be disable
otherwise the following err is thrown at configure.

```
ERROR: pixman disabled but system emulation or tools build
       enabled.  You can turn off pixman only if you also
       disable all system emulation targets and the tools
       build with '--disable-tools --disable-system'.
```

qemu-img seems to be built with these disabled.

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>